[2024-10-17T23:24:47.571+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T23:24:47.582+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_SCRIPT.EMAIL_FAILURE manual__2024-10-17T23:23:10.576662+00:00 [queued]>
[2024-10-17T23:24:47.588+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_SCRIPT.EMAIL_FAILURE manual__2024-10-17T23:23:10.576662+00:00 [queued]>
[2024-10-17T23:24:47.588+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T23:24:47.598+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): EMAIL_FAILURE> on 2024-10-17 23:23:10.576662+00:00
[2024-10-17T23:24:47.603+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=395) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T23:24:47.603+0000] {standard_task_runner.py:72} INFO - Started process 396 to run task
[2024-10-17T23:24:47.604+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_SCRIPT', 'EMAIL_FAILURE', 'manual__2024-10-17T23:23:10.576662+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag_file.py', '--cfg-path', '/tmp/tmpmcfm0zp6']
[2024-10-17T23:24:47.604+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask EMAIL_FAILURE
[2024-10-17T23:24:47.631+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_SCRIPT.EMAIL_FAILURE manual__2024-10-17T23:23:10.576662+00:00 [running]> on host f285080d593b
[2024-10-17T23:24:47.684+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='guilhermeavila.orlando@gmail.com' AIRFLOW_CTX_DAG_OWNER='Guilherme Orlando' AIRFLOW_CTX_DAG_ID='ETL_SCRIPT' AIRFLOW_CTX_TASK_ID='EMAIL_FAILURE' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T23:23:10.576662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T23:23:10.576662+00:00'
[2024-10-17T23:24:47.685+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T23:24:50.299+0000] {logging_mixin.py:190} INFO - E-mail enviado com sucesso!
[2024-10-17T23:24:50.299+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-17T23:24:50.308+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T23:24:50.309+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ETL_SCRIPT, task_id=EMAIL_FAILURE, run_id=manual__2024-10-17T23:23:10.576662+00:00, execution_date=20241017T232310, start_date=20241017T232447, end_date=20241017T232450
[2024-10-17T23:24:50.344+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-17T23:24:50.354+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T23:24:50.355+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
