[2024-10-17T23:18:34.388+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T23:18:34.400+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_SCRIPT.RUN_SILVER manual__2024-10-17T23:18:01.263969+00:00 [queued]>
[2024-10-17T23:18:34.405+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_SCRIPT.RUN_SILVER manual__2024-10-17T23:18:01.263969+00:00 [queued]>
[2024-10-17T23:18:34.406+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T23:18:34.415+0000] {taskinstance.py:2888} INFO - Executing <Task(DatabricksSubmitRunOperator): RUN_SILVER> on 2024-10-17 23:18:01.263969+00:00
[2024-10-17T23:18:34.420+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=289) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T23:18:34.421+0000] {standard_task_runner.py:72} INFO - Started process 290 to run task
[2024-10-17T23:18:34.421+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_SCRIPT', 'RUN_SILVER', 'manual__2024-10-17T23:18:01.263969+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_file.py', '--cfg-path', '/tmp/tmpsqumoj_m']
[2024-10-17T23:18:34.422+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask RUN_SILVER
[2024-10-17T23:18:34.450+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_SCRIPT.RUN_SILVER manual__2024-10-17T23:18:01.263969+00:00 [running]> on host f285080d593b
[2024-10-17T23:18:34.500+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='guilhermeavila.orlando@gmail.com' AIRFLOW_CTX_DAG_OWNER='Guilherme Orlando' AIRFLOW_CTX_DAG_ID='ETL_SCRIPT' AIRFLOW_CTX_TASK_ID='RUN_SILVER' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T23:18:01.263969+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T23:18:01.263969+00:00'
[2024-10-17T23:18:34.501+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T23:18:34.516+0000] {base.py:84} INFO - Retrieving connection 'databricks_default'
[2024-10-17T23:18:34.517+0000] {databricks_base.py:461} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2024-10-17T23:18:35.158+0000] {databricks.py:66} INFO - Run submitted with run_id: 621344661149242
[2024-10-17T23:18:35.158+0000] {databricks_base.py:461} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2024-10-17T23:18:35.264+0000] {databricks_base.py:461} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2024-10-17T23:18:35.359+0000] {databricks.py:128} INFO - RUN_SILVER in run state: {'life_cycle_state': 'PENDING', 'result_state': '', 'state_message': ''}
[2024-10-17T23:18:35.360+0000] {databricks.py:129} INFO - View run status, Spark UI, and logs at https://dbc-bc2bfcff-3ceb.cloud.databricks.com/?o=1271398189221813#job/1006476232331869/run/621344661149242
[2024-10-17T23:18:35.360+0000] {databricks.py:130} INFO - Sleeping for 30 seconds.
[2024-10-17T23:19:05.359+0000] {databricks_base.py:461} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2024-10-17T23:19:05.482+0000] {databricks_base.py:461} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2024-10-17T23:19:05.893+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/databricks/operators/databricks.py", line 628, in execute
    _handle_databricks_operator_execution(self, self._hook, self.log, context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/databricks/operators/databricks.py", line 126, in _handle_databricks_operator_execution
    raise AirflowException(error_message)
airflow.exceptions.AirflowException: RUN_SILVER failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': 'Workload failed, see run output for details'} and with the errors [{'task_key': 'Airflow_Databricks_Silver', 'run_id': 621344661149242, 'error': 'java.nio.file.AccessDeniedException: s3a://case-amb/raw/breweries_data.json: getFileStatus on s3a://case-amb/raw/breweries_data.json: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD https://case-amb.s3.sa-east-1.amazonaws.com raw/breweries_data.json {} Hadoop 3.3.6, aws-sdk-java/1.12.390 Linux/5.15.0-1070-aws OpenJDK_64-Bit_Server_VM/25.382-b05 java/1.8.0_382 scala/2.12.15 kotlin/1.6.0 vendor/Azul_Systems,_Inc. cfg/retry-mode/legacy com.amazonaws.services.s3.model.GetObjectMetadataRequest; Request ID: 0VZVKSB445YHQ2A1, Extended Request ID: BMESc+xaXiQngnqJMjLXTz+xUful+LJrAtjAUOlf4nhXuzt+EJkS6dkE55J8LdnIltjxZx6MUuw=, Cloud Provider: AWS, Instance ID: i-02fcf411ea5faf39a credentials-provider: com.amazonaws.auth.BasicAWSCredentials credential-header: AWS4-HMAC-SHA256 Credential=AKIA4RCAOODKCNGL7ANO/20241017/sa-east-1/s3/aws4_request signature-present: true (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 0VZVKSB445YHQ2A1; S3 Extended Request ID: BMESc+xaXiQngnqJMjLXTz+xUful+LJrAtjAUOlf4nhXuzt+EJkS6dkE55J8LdnIltjxZx6MUuw=; Proxy: null), S3 Extended Request ID: BMESc+xaXiQngnqJMjLXTz+xUful+LJrAtjAUOlf4nhXuzt+EJkS6dkE55J8LdnIltjxZx6MUuw=:403 Forbidden'}]
[2024-10-17T23:19:05.898+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_SCRIPT, task_id=RUN_SILVER, run_id=manual__2024-10-17T23:18:01.263969+00:00, execution_date=20241017T231801, start_date=20241017T231834, end_date=20241017T231905
[2024-10-17T23:19:05.918+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T23:19:05.918+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task RUN_SILVER (RUN_SILVER failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': 'Workload failed, see run output for details'} and with the errors [{'task_key': 'Airflow_Databricks_Silver', 'run_id': 621344661149242, 'error': 'java.nio.file.AccessDeniedException: s3a://case-amb/raw/breweries_data.json: getFileStatus on s3a://case-amb/raw/breweries_data.json: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD https://case-amb.s3.sa-east-1.amazonaws.com raw/breweries_data.json {} Hadoop 3.3.6, aws-sdk-java/1.12.390 Linux/5.15.0-1070-aws OpenJDK_64-Bit_Server_VM/25.382-b05 java/1.8.0_382 scala/2.12.15 kotlin/1.6.0 vendor/Azul_Systems,_Inc. cfg/retry-mode/legacy com.amazonaws.services.s3.model.GetObjectMetadataRequest; Request ID: 0VZVKSB445YHQ2A1, Extended Request ID: BMESc+xaXiQngnqJMjLXTz+xUful+LJrAtjAUOlf4nhXuzt+EJkS6dkE55J8LdnIltjxZx6MUuw=, Cloud Provider: AWS, Instance ID: i-02fcf411ea5faf39a credentials-provider: com.amazonaws.auth.BasicAWSCredentials credential-header: AWS4-HMAC-SHA256 Credential=AKIA4RCAOODKCNGL7ANO/20241017/sa-east-1/s3/aws4_request signature-present: true (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 0VZVKSB445YHQ2A1; S3 Extended Request ID: BMESc+xaXiQngnqJMjLXTz+xUful+LJrAtjAUOlf4nhXuzt+EJkS6dkE55J8LdnIltjxZx6MUuw=; Proxy: null), S3 Extended Request ID: BMESc+xaXiQngnqJMjLXTz+xUful+LJrAtjAUOlf4nhXuzt+EJkS6dkE55J8LdnIltjxZx6MUuw=:403 Forbidden'}]; 290)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/databricks/operators/databricks.py", line 628, in execute
    _handle_databricks_operator_execution(self, self._hook, self.log, context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/databricks/operators/databricks.py", line 126, in _handle_databricks_operator_execution
    raise AirflowException(error_message)
airflow.exceptions.AirflowException: RUN_SILVER failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': 'Workload failed, see run output for details'} and with the errors [{'task_key': 'Airflow_Databricks_Silver', 'run_id': 621344661149242, 'error': 'java.nio.file.AccessDeniedException: s3a://case-amb/raw/breweries_data.json: getFileStatus on s3a://case-amb/raw/breweries_data.json: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD https://case-amb.s3.sa-east-1.amazonaws.com raw/breweries_data.json {} Hadoop 3.3.6, aws-sdk-java/1.12.390 Linux/5.15.0-1070-aws OpenJDK_64-Bit_Server_VM/25.382-b05 java/1.8.0_382 scala/2.12.15 kotlin/1.6.0 vendor/Azul_Systems,_Inc. cfg/retry-mode/legacy com.amazonaws.services.s3.model.GetObjectMetadataRequest; Request ID: 0VZVKSB445YHQ2A1, Extended Request ID: BMESc+xaXiQngnqJMjLXTz+xUful+LJrAtjAUOlf4nhXuzt+EJkS6dkE55J8LdnIltjxZx6MUuw=, Cloud Provider: AWS, Instance ID: i-02fcf411ea5faf39a credentials-provider: com.amazonaws.auth.BasicAWSCredentials credential-header: AWS4-HMAC-SHA256 Credential=AKIA4RCAOODKCNGL7ANO/20241017/sa-east-1/s3/aws4_request signature-present: true (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 0VZVKSB445YHQ2A1; S3 Extended Request ID: BMESc+xaXiQngnqJMjLXTz+xUful+LJrAtjAUOlf4nhXuzt+EJkS6dkE55J8LdnIltjxZx6MUuw=; Proxy: null), S3 Extended Request ID: BMESc+xaXiQngnqJMjLXTz+xUful+LJrAtjAUOlf4nhXuzt+EJkS6dkE55J8LdnIltjxZx6MUuw=:403 Forbidden'}]
[2024-10-17T23:19:05.928+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-17T23:19:05.944+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T23:19:05.945+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
